name: tapeAA_env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.11
  - snakemake
  - fastqc
  - multiqc
  - fastp
  - salmon
  - star
  - subread
  - r-base=4.4
  - r-tidyverse
  - r-data.table
  - r-devtools
  - r-biocmanager

